version: '3.8'

services:
  app:
    build: .
    container_name: prueba_web
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/miapp
    depends_on:
      - mongo
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - app-network

  mongo:
    image: mongo:latest
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo_data:
